# Generated by Django 3.0.2 on 2020-04-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='duration',
            field=models.CharField(default='ongoing', max_length=20),
        ),
        migrations.AlterField(
            model_name='plans',
            name='plan_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('free', 'Free')], default='free', max_length=30),
        ),
    ]
