# Generated by Django 3.0.2 on 2020-04-09 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='date',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='sub_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.AddField(
            model_name='subscription',
            name='initiated_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan_type',
            field=models.CharField(choices=[('MONTHLY', 'Basic monthly plan (10kr/month)'), ('YEARLY', 'Two months free (100kr/year)'), ('THREE_YEAR', 'Four months free (280kr/3 years)')], default='MONTHLY', max_length=15),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(default=0, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='terminated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('stripe_customer_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_customer_id',
            field=models.ForeignKey(db_column='stripe_customer_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='payments.Customer'),
        ),
    ]
