# Generated by Django 3.0.2 on 2020-04-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30)),
                ('stripe_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='stripe_id',
            field=models.CharField(max_length=50),
        ),
    ]
