# Generated by Django 3.0.2 on 2020-04-27 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_plans_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
