# Generated by Django 3.0.2 on 2020-04-20 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20200419_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RemoveField(
            model_name='plans',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='plan_type',
        ),
        migrations.AddField(
            model_name='customer',
            name='sub',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='payments.Plans'),
        ),
        migrations.AddField(
            model_name='plans',
            name='plan_type',
            field=models.CharField(choices=[('MONTHLY', 'monthly'),
                                            ('YEARLY', 'yearly'),
                                            ('FREE', 'Free')],
                                   default='FREE',
                                   max_length=30),
        ),
        migrations.AddField(
            model_name='plans',
            name='price',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='id',
            field=models.AutoField(auto_created=True,
                                   default=0,
                                   primary_key=True,
                                   serialize=False,
                                   verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='user_customer',
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to='payments.Customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(max_length=50),
        ),
    ]
