# Generated by Django 3.0.2 on 2020-04-20 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20200420_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user',
            new_name='user_customer',
        ),
    ]
