# Generated by Django 3.0.1 on 2020-01-11 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='superuser',
        ),
    ]
