# Generated by Django 3.0.2 on 2020-04-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
