# Generated by Django 3.0.1 on 2020-01-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth', '0002_remove_customuser_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password2',
            field=models.CharField(default='abc123', max_length=128),
            preserve_default=False,
        ),
    ]
