# Generated by Django 3.0.2 on 2020-04-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth', '0002_auto_20200426_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='complete_signup',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
