# Generated by Django 3.0.2 on 2020-04-20 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=5000)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('personnummer', models.CharField(max_length=12)),
                ('street', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('consent', models.BooleanField(blank=True)),
                ('sub_type', models.CharField(default=0, max_length=20)),
                ('clinics', models.ManyToManyField(to='clinic.Clinic')),
                ('mods', models.ManyToManyField(blank=True, to='accounts.Modalities')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
