# Generated by Django 3.0.2 on 2020-02-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalities',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
