# Generated by Django 3.0.1 on 2020-01-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modalities',
            name='mod_name',
        ),
        migrations.AddField(
            model_name='modalities',
            name='mods',
            field=models.CharField(default='mod', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='mods',
            field=models.CharField(max_length=500),
        ),
    ]
