# Generated by Django 2.2.9 on 2020-01-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '__first__'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='clinics',
            field=models.ManyToManyField(to='clinic.Clinic'),
        ),
    ]
