# Generated by Django 3.0.1 on 2020-01-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200113_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='mods',
            field=models.ManyToManyField(to='accounts.Modalities'),
        ),
    ]
