# Generated by Django 2.2.9 on 2020-02-10 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(max_length=128)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('description', models.TextField(max_length=5000)),
                ('street', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('practitioner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_prac', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
