# Generated by Django 3.0.2 on 2020-02-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='web',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
