# Generated by Django 3.0.2 on 2020-02-24 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_auto_20200224_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='reviews',
        ),
        migrations.AddField(
            model_name='reviews',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.Clinic'),
        ),
    ]
