# Generated by Django 3.0.2 on 2020-02-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_auto_20200224_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='body',
            field=models.TextField(max_length=500),
        ),
    ]
