# Generated by Django 3.0.2 on 2020-02-18 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_auto_20200211_0732'),
        ('clinic', '0006_auto_20200215_1052'),
    ]

    operations = [
    ]
